[build]
  publish = "tabaccheriapro/dist"
  command = "cd tabaccheriapro && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
