export const BUSINESS_TYPES = {
  RESTAURANT: {
    label: 'Ristorante',
    icon: 'UtensilsCrossed',
    serviceLabel: 'Piatti / Menu',
    bookingLabel: 'Prenotazione Tavolo',
    hasNumberOfPeople: true,
    defaultCategories: ['Antipasti', 'Primi', 'Secondi', 'Contorni', 'Dolci', 'Bevande'],
  },
  HAIR_SALON: {
    label: 'Parrucchiere',
    icon: 'Scissors',
    serviceLabel: 'Servizi',
    bookingLabel: 'Appuntamento',
    hasNumberOfPeople: false,
    defaultCategories: ['Taglio', 'Colore', 'Trattamenti', 'Styling'],
  },
  BEAUTY_CENTER: {
    label: 'Centro Estetico',
    icon: 'Sparkles',
    serviceLabel: 'Trattamenti',
    bookingLabel: 'Appuntamento',
    hasNumberOfPeople: false,
    defaultCategories: ['Viso', 'Corpo', 'Mani e Piedi', 'Depilazione', 'Massaggi'],
  },
  MEDICAL_OFFICE: {
    label: 'Studio Medico',
    icon: 'Stethoscope',
    serviceLabel: 'Visite',
    bookingLabel: 'Appuntamento',
    hasNumberOfPeople: false,
    defaultCategories: ['Visite Generiche', 'Visite Specialistiche', 'Esami', 'Certificati'],
  },
  DENTAL_OFFICE: {
    label: 'Studio Dentistico',
    icon: 'HeartPulse',
    serviceLabel: 'Trattamenti',
    bookingLabel: 'Appuntamento',
    hasNumberOfPeople: false,
    defaultCategories: ['Igiene', 'Conservativa', 'Protesi', 'Ortodonzia', 'Chirurgia'],
  },
  HOTEL: {
    label: 'Hotel / B&B',
    icon: 'Hotel',
    serviceLabel: 'Camere / Servizi',
    bookingLabel: 'Prenotazione Camera',
    hasNumberOfPeople: true,
    defaultCategories: ['Camere', 'Suite', 'Servizi Extra', 'Ristorazione'],
  },
  GYM: {
    label: 'Palestra',
    icon: 'Dumbbell',
    serviceLabel: 'Corsi / Abbonamenti',
    bookingLabel: 'Prenotazione Corso',
    hasNumberOfPeople: false,
    defaultCategories: ['Sala Pesi', 'Corsi di Gruppo', 'Personal Training', 'Abbonamenti'],
  },
  SPORTS_CENTER: {
    label: 'Centro Sportivo',
    icon: 'Trophy',
    serviceLabel: 'Campi / Attività',
    bookingLabel: 'Prenotazione Campo',
    hasNumberOfPeople: true,
    defaultCategories: ['Padel', 'Tennis', 'Calcetto', 'Basket', 'Nuoto'],
  },
  VETERINARY: {
    label: 'Veterinario',
    icon: 'PawPrint',
    serviceLabel: 'Visite / Servizi',
    bookingLabel: 'Appuntamento',
    hasNumberOfPeople: false,
    defaultCategories: ['Visite', 'Vaccinazioni', 'Chirurgia', 'Esami', 'Toelettatura'],
  },
  REAL_ESTATE: {
    label: 'Agenzia Immobiliare',
    icon: 'Building2',
    serviceLabel: 'Servizi',
    bookingLabel: 'Appuntamento Visita',
    hasNumberOfPeople: false,
    defaultCategories: ['Vendita', 'Affitto', 'Valutazioni', 'Consulenza'],
  },
  AUTO_REPAIR: {
    label: 'Officina / Carrozzeria',
    icon: 'Wrench',
    serviceLabel: 'Servizi',
    bookingLabel: 'Appuntamento',
    hasNumberOfPeople: false,
    defaultCategories: ['Tagliando', 'Revisione', 'Carrozzeria', 'Gomme', 'Elettrauto'],
  },
  BAKERY: {
    label: 'Pasticceria / Panificio',
    icon: 'CakeSlice',
    serviceLabel: 'Prodotti',
    bookingLabel: 'Ordine',
    hasNumberOfPeople: false,
    defaultCategories: ['Pane', 'Dolci', 'Torte su Ordinazione', 'Salato'],
  },
  BAR: {
    label: 'Bar / Caffetteria',
    icon: 'Coffee',
    serviceLabel: 'Menu',
    bookingLabel: 'Prenotazione',
    hasNumberOfPeople: true,
    defaultCategories: ['Caffetteria', 'Colazione', 'Aperitivi', 'Cocktails', 'Snack'],
  },
  CATERING: {
    label: 'Catering / Banqueting',
    icon: 'ChefHat',
    serviceLabel: 'Menu / Pacchetti',
    bookingLabel: 'Preventivo',
    hasNumberOfPeople: true,
    defaultCategories: ['Menu Completi', 'Buffet', 'Finger Food', 'Dolci', 'Bevande'],
  },
  PHARMACY: {
    label: 'Farmacia',
    icon: 'Pill',
    serviceLabel: 'Servizi',
    bookingLabel: 'Prenotazione',
    hasNumberOfPeople: false,
    defaultCategories: ['Farmaci', 'Parafarmaci', 'Consulenze', 'Servizi Sanitari'],
  },
  OTHER: {
    label: 'Altra Attività',
    icon: 'Store',
    serviceLabel: 'Servizi',
    bookingLabel: 'Appuntamento',
    hasNumberOfPeople: false,
    defaultCategories: ['Servizio 1', 'Servizio 2', 'Servizio 3'],
  },
} as const

export type BusinessType = keyof typeof BUSINESS_TYPES
